### ISSUE TITLE
Any sample flow ?

### ISSUE THREAD

**Issue by ylecleach** [DeanCording/node-red-contrib-assert#1]
Hi Dean, 
do you have some sample flow or a tutorial that explains how use your node ?
Thank you.

Yves (from Watson Developer Cloud / Node-RED Team)

**Comment by DeanCording** [comment]
Here is a sample flow:

[{"id":"ede6fe04.eded3","type":"assert","z":"8b42e25d.61776","name":"Payload < 100","rules":[{"property":"payload","propertyType":"msg","type":"lt","value":"100","valueType":"num"}],"x":442.5,"y":442,"wires":[["4fd55a87.740b74"]]},{"id":"4fd55a87.740b74","type":"debug","z":"8b42e25d.61776","name":"","active":true,"console":"false","complete":"false","x":670.5,"y":445,"wires":[]},{"id":"5f32bb08.e7a17c","type":"inject","z":"8b42e25d.61776","name":"","topic":"","payload":"50","payloadType":"num","repeat":"","crontab":"","once":false,"x":172.5,"y":440,"wires":[["ede6fe04.eded3"]]},{"id":"cb3d81c3.e0ecb8","type":"inject","z":"8b42e25d.61776","name":"","topic":"","payload":"150","payloadType":"num","repeat":"","crontab":"","once":false,"x":140.5,"y":513,"wires":[["ede6fe04.eded3"]]},{"id":"ef019fc4.e98a2","type":"catch","z":"8b42e25d.61776","name":"Assert failed","scope":["ede6fe04.eded3"],"x":448.5,"y":522,"wires":[["ff38f898.9fb15"]]},{"id":"ff38f898.9fb15","type":"debug","z":"8b42e25d.61776","name":"","active":true,"console":"false","complete":"error.message","x":697.5,"y":519,"wires":[]}]

**Comment by DeanCording** [comment]
Added a sample flow to the Readme.md
