### ISSUE TITLE
Allow to specify custom error messages

### ISSUE THREAD

**Issue by whiver** [DeanCording/node-red-contrib-assert#3]
Hi,

I would like to know if it would be possible to add a new feature in the node. In fact, when you have several rules in the assert node, the catch node might not be able to deliver a precise message, depending on the specific rule that failed.

That's why I would like to know if it is or would be possible to add a (maybe optional) field to customize the `msg.error.message` field for each rule, in order to have more precise error messages, without the technical explanation.

Thank you in advance for your answer and thank you for this great node.

**Comment by DeanCording** [comment]
This should be possible.  Give me a few days to have a look.

**Comment by whiver** [comment]
Thank you! That's awesome :)

**Comment by DeanCording** [comment]
I've added the ability to add custom text that gets appended to the error message.
